### PR TITLE
Fixed mapping errors

### LINKED ISSUE #120: Map does not currently display location correctly for snapshots or players in bubble
The player's bubble is not currently being set correctly and all players currently exist in the off campus bubble. Debugging why to make these display correctly.

### PR DESCRIPTION
**Pull request by noahklowden**
The player's location would not be uploaded to the database and also they would not show the correct map location for each player. This PR solves this by adding missing databaseUpdates for the global player location and also fixing an issue where all of the campus map locations had their lattitude and longitude reversed.

Closes #120

### CODE REVIEW

File: appGeo/src/app/map/campus-map.component.ts [hunk 1]
```diff
@@ -105,229 +107,231 @@ export class CampusMap implements OnInit {
...
       if(global.playerlist){
         /*if a global playerlist exists
         takes in the global playerlists values to set up the map*/
         for (let user of global.playerlist.values()) {
+          console.log("User location is: " + user.location)
           this.playerInBubble(user)
         }
       }
 
+      console.log("player location is: ", player.location)
```
Comment (jasulcaf) [inline appGeo/src/app/map/campus-map.component.ts:334]: Same as above^

**Review by jasulcaf — APPROVED** [review]
Looks good to me, only have 2 minor comments that don't impact the actual functionality of the code but rather console.log
